name: Build Windows Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools

    - name: Install main dependencies
      run: |
        pip install -r requirements.txt

    - name: Install development dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --name VectorAnalyzer `
          --onefile `
          --windowed `
          --icon=src/resources/icon.ico `
          --add-data "src/resources;src/resources" `
          --hidden-import="numpy" `
          --hidden-import="matplotlib" `
          --hidden-import="pandas" `
          --hidden-import="PyQt6" `
          --hidden-import="openpyxl" `
          --collect-data matplotlib `
          --collect-data PyQt6 `
          src/main.py

    # Используем новую версию action с поддержкой node20
    - name: Create Release and Upload Asset
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./dist/VectorAnalyzer.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release v${{ github.run_number }}
        tag: v${{ github.run_number }}
        draft: false
        prerelease: false
        generateReleaseNotes: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VectorAnalyzer-Windows
        path: dist/VectorAnalyzer.exe
        retention-days: 90